// <auto-generated />
using System;
using MiConsorcio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiConsorcio.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230161054_NewInitialClean")]
    partial class NewInitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiConsorcio.Domain.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasGasto");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Consorcio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Consorcios", (string)null);
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Expensa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("Expensas");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.ExpensaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpensaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UnidadFuncionalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpensaId");

                    b.ToTable("ExpensaDetalles", (string)null);
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedioPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UnidadFuncionalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cuil")
                        .IsUnique();

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.UnidadFuncional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Coeficiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ConsorcioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("Piso")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("UnidadesFuncionales");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.UnidadFuncionalPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadFuncionalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UFPersonas");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Consorcio", b =>
                {
                    b.OwnsOne("MiConsorcio.Domain.Models.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ConsorcioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CodigoPostal");

                            b1.HasKey("ConsorcioId");

                            b1.ToTable("Consorcios");

                            b1.WithOwner()
                                .HasForeignKey("ConsorcioId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Expensa", b =>
                {
                    b.HasOne("MiConsorcio.Domain.Models.Consorcio", "Consorcio")
                        .WithMany("Expensas")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("MiConsorcio.Domain.Models.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("ExpensaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Anio")
                                .HasColumnType("int")
                                .HasColumnName("PeriodoAnio");

                            b1.Property<int>("Mes")
                                .HasColumnType("int")
                                .HasColumnName("PeriodoMes");

                            b1.HasKey("ExpensaId");

                            b1.HasIndex("Anio", "Mes")
                                .IsUnique();

                            b1.ToTable("Expensas");

                            b1.WithOwner()
                                .HasForeignKey("ExpensaId");
                        });

                    b.Navigation("Consorcio");

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.ExpensaDetalle", b =>
                {
                    b.HasOne("MiConsorcio.Domain.Models.Expensa", "Expensa")
                        .WithMany("Detalles")
                        .HasForeignKey("ExpensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expensa");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Gasto", b =>
                {
                    b.HasOne("MiConsorcio.Domain.Models.Consorcio", null)
                        .WithMany("Gastos")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("MiConsorcio.Domain.Models.Periodo", "PeriodoContable", b1 =>
                        {
                            b1.Property<Guid>("GastoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Anio")
                                .HasColumnType("int")
                                .HasColumnName("PeriodoAno");

                            b1.Property<int>("Mes")
                                .HasColumnType("int")
                                .HasColumnName("PeriodoMes");

                            b1.HasKey("GastoId");

                            b1.ToTable("Gastos");

                            b1.WithOwner()
                                .HasForeignKey("GastoId");
                        });

                    b.Navigation("PeriodoContable")
                        .IsRequired();
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Pago", b =>
                {
                    b.HasOne("MiConsorcio.Domain.Models.Consorcio", null)
                        .WithMany("Pagos")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Persona", b =>
                {
                    b.OwnsOne("MiConsorcio.Domain.Models.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("PersonaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CodigoPostal");

                            b1.HasKey("PersonaId");

                            b1.ToTable("Personas");

                            b1.WithOwner()
                                .HasForeignKey("PersonaId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.UnidadFuncional", b =>
                {
                    b.HasOne("MiConsorcio.Domain.Models.Consorcio", null)
                        .WithMany("Unidades")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("MiConsorcio.Domain.Models.SaldoUF", "Saldo", b1 =>
                        {
                            b1.Property<Guid>("UnidadFuncionalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Saldo");

                            b1.HasKey("UnidadFuncionalId");

                            b1.ToTable("UnidadesFuncionales");

                            b1.WithOwner()
                                .HasForeignKey("UnidadFuncionalId");
                        });

                    b.Navigation("Saldo")
                        .IsRequired();
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Consorcio", b =>
                {
                    b.Navigation("Expensas");

                    b.Navigation("Gastos");

                    b.Navigation("Pagos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("MiConsorcio.Domain.Models.Expensa", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
